In [11]:
import numpy as np
import pandas as pd

x = np.random.randn(5,6)
w = np.random.randn(5,6)
b = 0.5

print(x)
print(w)

[[-0.3343452   0.73969226  0.45246482  0.70088887 -0.29184665  1.92260538]
 [-0.23222098 -1.51610866  0.83717629  1.71754078  0.12488977  0.06724792]
 [-0.79410155 -2.36688073 -1.20618998  0.77543526 -0.1146819   0.22839057]
 [-0.03445117 -0.64655579  0.93995105 -1.28456894  1.45647772 -0.57172758]
 [-1.47649368  0.24387083  1.30788414 -1.14086451 -0.65862401  0.62903651]]
[[-1.45796474e+00 -4.15073843e-01  5.22032229e-01  8.01042941e-01
  -3.41576037e-01 -4.63362972e-01]
 [ 6.55983085e-01 -1.48192311e+00  1.35830486e+00  5.45804874e-01
  -1.30486557e-01 -1.57433962e-01]
 [ 4.60355873e-01  1.75103889e-01  3.80628054e-01  7.18148256e-01
   2.29863843e-01 -1.94627564e+00]
 [-4.61726192e-02 -2.09108548e+00  6.51247049e-01  5.05412440e-01
   1.02843363e+00  8.05296410e-01]
 [ 1.43680529e-01 -3.28406123e-02  1.71916215e+00 -8.84324210e-01
  -1.70780862e-03 -7.29561660e-01]]


In [12]:
Z = np.dot(w.T,x)+b
print(Z)

X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]]) #特征矩阵，每一行代表一个样本，每一列代表一个特征
y = np.array([0, 0, 1, 1]) #真实标签向量
print(X)
print(y)

[[ 0.25900846 -2.59770165 -0.02126342  0.85717452  0.79275238 -2.03705796]
 [ 0.96439061  3.36927408 -3.14811548  0.52320787 -2.60801017  0.81718592]
 [-2.85299145 -2.07590982  4.27483735  0.69608017  0.28987922  2.39101687]
 [ 0.82343221 -1.97718371 -0.22837523  2.91541867  1.57058426  1.39558155]
 [ 0.42906162 -0.76424585  0.9233928  -1.10442381  2.05604564 -0.70205029]
 [ 3.28647294  4.30395544  2.30887983 -1.80650371  2.49217474 -1.76529333]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]]
[0 0 1 1]


In [9]:
class LogisticRegression:
    def __init__(self, learning_rate=0.01, num_iterations=1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
        self.weights = None #weights 用于存储模型的权重，初始化为 None
        self.bias = None #bias 用于存储模型的偏置，初始化为 None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        num_samples, num_features = X.shape #X.shape 返回特征矩阵 X 的形状，是一个包含两个元素的元组，分别表示样本数量和特征数量
        self.weights = np.zeros(num_features) #np.zeros(num_features) 创建一个长度为 num_features 的全零数组，将其赋值给 self.weights，作为权重的初始值
        self.bias = 0 #将偏置 self.bias 初始化为 0

        for _ in range(self.num_iterations):
            linear_model = np.dot(X, self.weights) + self.bias #即Z = np.dot(w.T,x)+b
            y_pred = self.sigmoid(linear_model)

            dw = (1 / num_samples) * np.dot(X.T, (y_pred - y)) #计算损失函数关于权重的梯度，除以样本数量是为了求平均梯度
            db = (1 / num_samples) * np.sum(y_pred - y) #计算损失函数关于偏置的梯度，同样除以样本数量求平均梯度

            self.weights -= self.learning_rate * dw 
            self.bias -= self.learning_rate * db #计算损失函数关于偏置的梯度，同样除以样本数量求平均梯度

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_pred = self.sigmoid(linear_model)
        y_pred_cls = [1 if i > 0.5 else 0 for i in y_pred] #使用列表推导式，将预测概率大于 0.5 的样本预测为 1，否则预测为 0
        return np.array(y_pred_cls) #将预测结果列表转换为 numpy 数组并返回

# 示例数据
X = np.array([[1, 2], [2, 3], [3, 4], [4, 5]]) #特征矩阵，每一行代表一个样本，每一列代表一个特征
y = np.array([0, 0, 1, 1]) #真实标签向量

# 创建逻辑回归模型实例
model = LogisticRegression(learning_rate=0.01, num_iterations=1000)

# 训练模型
model.fit(X, y)

# 进行预测
predictions = model.predict(X)
print("预测结果:", predictions)

预测结果: [0 1 1 1]


In [8]:
file_path = r'D:\desktop\唐雨珂\机器学习\logit.xlsx' 
data = pd.read_excel(file_path)
#print(data) 默认第一行为索引没有实际用途，使用时真正的特征数据从第二行开始

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values
model = LogisticRegression(learning_rate=0.01, num_iterations=1000)
model.fit(X, y)
predictions = model.predict(X)
print("预测结果:", predictions)


预测结果: [0 1 1 1]
